"""Pydantic models and schemas defining API data contracts."""

from typing import List, Optional
from pydantic import BaseModel, Field


class QualityMetrics(BaseModel):
    width: int = Field(..., description="Image width in pixels", examples=[1920])
    height: int = Field(..., description="Image height in pixels", examples=[1080])
    luminance: float = Field(..., description="Mean perceived luminance (0-255)", examples=[115.4])
    sharpness_score: float = Field(..., description="Laplacian variance sharpness score", examples=[95.2])
    luminance_status: str = Field(..., description="OPTIMAL, UNDEREXPOSED, or OVEREXPOSED", examples=["OPTIMAL"])
    sharpness_status: str = Field(..., description="SHARP or BLURRY", examples=["SHARP"])


class VisualInspectionResponse(BaseModel):
    correlation_id: str = Field(..., description="Correlation ID for end-to-end request tracing", examples=["corr-12345"])
    inspection_id: str = Field(..., description="Inspection identifier", examples=["INSP-001"])
    room_id: str = Field(..., description="Room identifier", examples=["room-101"])
    metrics: QualityMetrics
    warnings: List[str] = Field(default_factory=list, description="List of quality warning codes", examples=[[]])
    assessment: str = Field(..., description="EVIDENCE_VALID or EVIDENCE_REQUIRES_RETAKE", examples=["EVIDENCE_VALID"])


class ProblemDetails(BaseModel):
    type: str = Field(..., description="URI reference identifying the problem type", examples=["https://hotel.local/errors/invalid-image"])
    title: str = Field(..., description="Short, human-readable summary of problem", examples=["Invalid Image File"])
    status: int = Field(..., description="HTTP status code generated by origin server", examples=[400])
    detail: str = Field(..., description="Human-readable explanation specific to this occurrence", examples=["The uploaded file could not be decoded as a valid image."])
    instance: str = Field(..., description="URI reference identifying the specific occurrence of the problem", examples=["/v1/visual-inspections"])


class HealthzResponse(BaseModel):
    status: str = Field(..., description="Service health state", examples=["UP"])
